### ISSUE TITLE
Authenticate doesn't work out of the box

### ISSUE THREAD

**Issue by laurensiusadi** [marshallswain/feathers-pinia#35]
I just started a new project to move my older one to this new stack: Vue 3, Pinia, Feathers-Pinia. So I'm new to this.

Version:
```
"feathers-pinia": "^0.29.5",
"pinia": "^2.0.11",
"vue": "^3.2.30",
```

I found a bug when calling `auth.authenticate`.
The call to `feathersClient.authenticate` went through and got the response.
The error occurs here https://github.com/marshallswain/feathers-pinia/blob/main/src/define-auth-store.ts#L45
It can't assign `this` with the new object response to replace state.
Error message: `TypeError: 'set' on proxy: trap returned falsish for property 'user'`

Here's how I fixed it in my auth store:
```
async authenticate(authData) {
  try {
    const response = await feathersClient.authenticate(authData)
    Object.assign(this.$state, { ...response, isAuthenticated: true })
    return this.handleResponse(response) || response
  } catch (error) {
    this.error = error
    return this.handleError(error)
  }
},
```
The only fix being `this.$state` instead of just `this`.

**Comment by gustojs** [comment]
Can you paste your implementation please?

**Comment by laurensiusadi** [comment]
I wrote it there. `this.$state` instead of `this` being the only thing differs from the original implementation.

**Comment by laurensiusadi** [comment]
Here's my code so far:

```typescript
// store/auth.ts

import { defineAuthStore } from 'feathers-pinia'
import { api as feathersClient } from '../feathers'
import { useCaslStore } from './casl'
import { useUsers } from './users'

export const useAuth = defineAuthStore({
  feathersClient,
  state: () => ({
    userId: null
  }),
  getters: {
    user() {
      const user = useUsers()
      return this.userId ? user.getFromStore(this.userId) : null
    },
  },
  actions: {
    async authenticate(authData: any) {
      try {
        this.isLoading = true
        const response = await feathersClient.authenticate(authData)
        Object.assign(this.$state, { ...response, isAuthenticated: true })
        this.isLoading = false
        return this.handleResponse(response) || response
      } catch (error) {
        this.error = error
        return this.handleError(error)
      }
    },
    handleResponse(response: any) {
      this.userId = response.user.id
      const user = useUsers()
      user.addToStore(response.user)
      if (response.rules) {
        const casl = useCaslStore()
        casl.setRules(response.rules || [])
      }
      return response
    },
    async logout() {
      await feathersClient.logout()
      this.userId = null
      useCaslStore().setRules([])
    },
  }
})

```

```typescript
// store/users.ts

import { defineStore, BaseModel } from './index'
import { api } from '../feathers'

export class User extends BaseModel {
  static modelName = 'User'
  static instanceDefaults() {
    return {
      name: '',
      email: '',
    }
  }
}

const servicePath = 'users'
export const useUsers = defineStore({ servicePath, Model: User })

api.service(servicePath).hooks({})
```

```typescript
// store/index.ts

import { createPinia } from 'pinia'
import { setupFeathersPinia } from 'feathers-pinia'
import { api } from '../feathers'

export const pinia = createPinia()

export const { defineStore, BaseModel } = setupFeathersPinia({
  clients: { api },
  idField: 'id',
})
```

```typescript
// main.ts

import { createApp } from 'vue'
import { abilitiesPlugin } from '@casl/vue'

import App from './App.vue'
import { pinia } from './store'
import { useCaslStore } from './store/casl'
import { router } from './router'
import './assets/styles/index.css'

const app = createApp(App)
app.use(pinia)
app.use(abilitiesPlugin, useCaslStore().ability)
app.use(router)
app.mount('#app')

```

And here's how I use it inside `Login.vue`

```typescript
import { useAuth } from '../store/auth'
const auth = useAuth()

auth.authenticate({
  strategy: 'local',
  email: email.value,
  password: password.value
})
```

Hope these code helps you finding out the problem.
Thanks!

**Comment by zwe1ch** [comment]
I think i have the same problem. I followed the example from the documentation (https://feathers-pinia.pages.dev/guide/auth-stores.html#setup) and created the authStore as described there.
```
const authStore = defineAuthStore({
  feathersClient,
  state: () => ({
    userId: null
  }),
  getters: {
    user() {
      return this.userId ? User.getFromStore(this.userId) : null
    },
  },
  actions: {
    handleResponse(response: any) {
      this.userId = response.user.id || response.user._id
      User.addToStore(response.user)
      return response
    },
  },
})
```
After successful authentication I get the following error.

`Uncaught (in promise) TypeError: proxy set handler returned false for property '"user"'`

However, this is only the case if the getter is called `user()`. If I rename the getter, let's say to `foo()`, then it works and there is no error message anymore.

In both cases, however, the state of `isLoading` is never changed from `true` to `false`.

**Comment by MajesticPotatoe** [comment]
Came across this issue too. The issue probably is the that `authenticate()` returns the **user** object and tries to set it, but the pinia store already contains a **user** getter from the example and throws the error. 

Also noticed that auth service are also missing 2 functions that would be very helpful: `logout` and `reAuthenticate` (easy enough just to implement user side now, but would be worthwhile including). `logout` can be implemented like up above, `reAuthenticate` pretty much can be implemented the same way `authenticate` is just without passing authData

I also noticed some issue with `User.addToStore` not being available in the current example, had to pull and call `useUser()`

**Comment by tvld** [comment]
It's December 2022 and the issues are still there:
- no reAuthenticate (essential)
- no logout (essential)
- breaking type errors if you follow the documentation to the letter

**Comment by marshallswain** [comment]
> @marshallswain any idea why this issue is closed, as there are still two breaking issues and two important ones?

This issue is open?  Were you talking about another issue? OH, maybe you're talking about #53.  The auth issues are all fixed by using the new `useAuth` utility in the pre-release.  The `defineAuthStore` plugin is too restrictive for me to continue to support.  The `useAuth` utility can handle pretty much any use case, while also being really straightforward to use in the most basic authentication scenarios.  You can learn about it, here: https://v1.feathers-pinia.pages.dev/guide/use-auth.html

> It's December 2022 and the issues are still there

True.  The `defineAuthStore` plugin was brought over from Feathers-Vuex, but I couldn't figure out how to make it flexible enough.  I pride myself in being a very generous man when it comes to my time helping new devs, but the `defineAuthStore` plugin has stretched beyond the limit because it is not easily extensible.  It only works for one scenario, but then as soon as you need to implement the simplest of feature on top of it, it's not very apparent to people how to do it.  This is mostly related to the Options API style of the `defineAuthStore` utility.   This is why I love the new `useAuth` utility: you can build whatever you want with it, but the basic Feathers Authentication use case is designed to just work.

The types have sucked, and it wasn't until recently that I finally figured out that dropping model classes dramatically simplifies the types.   The new `useService` PR (which I've literally put hundreds of hours into) addresses the type-related problems.

One more thing: I apologize for the lousy experience you've had, and you're not alone.  I've learned that using TypeScript for the type of code that goes into a project is MUCH simpler than writing TypeScript code for a reusable package.  Back in JS-only days, I would have shipped this a long time ago, and fixed the bugs that came up.  But I've really wanted to offer a first-class TypeScript experience in Feathers-Pinia.  What I recently learned is that the overhead is far too big when using TS classes.   The latest version of TS has implemented a change to classes which is currently a stage 3 proposal in EcmaScript, but it makes it miserable to work with classes the way we have for years.  I won't go into the details, but the solution is the giant PR I'm working on with the `useService` feature.  It's really great because you install your typescript types generated by Dove into your client project and use them to build Model functions (think BaseModel classes, but purely functional).  The TypeScript experience is stellar, but it's a couple of weeks away from being ready for use.  I'm shooting for Christmas. 🎄 

Anyway, again I apologize for the junk experience.  Things have not gone according to plan, and only in the last couple of months have I finally figured out the solution.  It will be a breaking change, but very manageable.

**Comment by marshallswain** [comment]
I'm going to close this now that version 2.0's `useAuth` utility has fixes for all of the issues. https://v2.feathers-pinia.pages.dev/guide/use-auth.html
