### ISSUE TITLE
Example with typescript

### ISSUE THREAD

**Issue by bzd2000** [marshallswain/feathers-pinia#50]
Hello,

could you give an example with typescript ?
It’s not clear for me how and where to define the types of a model.

Thx,
Filip

**Comment by bzd2000** [comment]
Hello,

Currently I have an interface like

```
export interface ProjectModel extends BaseModel {
    _id: string;
    name: string;
    customerId: string;
}
```

and in my vue page

`const projects = projectsData.items as ComputedRef<ProjectModel[]>
`

Not sure this is the right way

**Comment by emmanuelgeoffray** [comment]
I've made a demo on how to use TypeScript with Feathers-Pinia : https://codesandbox.io/s/nostalgic-phoebe-4u1kb6?file=/src/stores/user.ts

It would be nice to mention that instead of having a '!' on each property, you can also use "strictPropertyInitialization": false in tsconfig.json

@marshallswain Let me know if I can write a section in the docs about TypeScript

**Comment by marshallswain** [comment]
@emmanuelgeoffray, In the next few weeks, I'll be updating the docs to the latest version of Vitepress.  You can submit some docs in the near future or after I make the change.  That would be awesome. thank you.

**Comment by marshallswain** [comment]
I'm going to go ahead and close this since we now have the [Vite example](https://v1.feathers-pinia.pages.dev/guide/setup-vite.html) and [Nuxt3 example](https://v1.feathers-pinia.pages.dev/guide/setup-nuxt3.html) apps in the documentation.

Also @bzd2000, a `class` also does double duty as an interface.  So you get TS support just by declaring the class.
