### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'clone')

### ISSUE THREAD

**Issue by ryaposov** [marshallswain/feathers-pinia#93]
In case an error happens during server patch request [on line 357](https://github.com/marshallswain/feathers-pinia/blob/71a9b39dd9b73babf17b52420b9bf53456f9ec9b/src/service-store/base-model.ts#L357), `saved` variable will be undefined.

That results in the following error below on line  366.
> TypeError: Cannot read properties of undefined (reading 'clone')

https://github.com/marshallswain/feathers-pinia/blob/71a9b39dd9b73babf17b52420b9bf53456f9ec9b/src/service-store/base-model.ts#L335-L367

**Comment by marshallswain** [comment]
Thanks for filing the issue. I'm going to address this as part of my giant `useService` PR, which you can follow here if you're feeling like reading a plus ultra ton of code: https://github.com/marshallswain/feathers-pinia/pull/92.  Docs will come soon.  The other PR is my laser focus right now, because it makes the feathers-pinia experience 1000x nicer and FeathersJS Dove/TypeScript friendly.  So this will remain open for a couple of weeks.

**Comment by marshallswain** [comment]
This should now be fixed in the latest 2.0 pre-release.  The code is immune to the original error you posted, since it's all done in hooks, now.  You've also made a good point about the error being swallowed, so now the latest code rethrows as you suggested.  Thank you!

See the latest code, here: https://github.com/marshallswain/feathers-pinia/blob/v2/src/hooks/hook-patch-diffs.ts#L45-L49

Here's the release with the fix: https://github.com/marshallswain/feathers-pinia/releases/tag/v2.0.0-pre.9
