### ISSUE TITLE
Setup experience - 1 - Adding Feathers-pinia if there is already Pinia installed

### ISSUE THREAD

**Issue by tvld** [marshallswain/feathers-pinia#94]
Currently trying to get Feathers Pinia installed. The doc's look awesome, so I thought peace of cake:

If you already have Pinia in your app, I suppose we can use the existing file? Maybe add this to the docs?

```ts
// src/plugins/pinia.ts
import { createPinia } from 'pinia'

// The setupFeathersPinia utility wraps defineStore
// ... provides a global configuration
// https://feathers-pinia.pages.dev/guide/setup.html#pinia

import { api } from '../feathers'
import { setupFeathersPinia } from 'feathers-pinia'

export const { defineStore, BaseModel } = setupFeathersPinia({
  clients: { api },
  idField: '_id'
})

// Feathers and other Pinia stores
//
export default createPinia()

```

**Comment by marshallswain** [comment]
Thanks @tvld.  Please take a look at the new docs page.  I've created installation instructions for [vite](https://v1.feathers-pinia.pages.dev/guide/setup-vite.html), and [Nuxt](https://v1.feathers-pinia.pages.dev/guide/setup-nuxt3.html). 

After I finish the `useService` PR, I'll do another pass at the installation docs and incorporate your idea.  Thank you!

**Comment by tvld** [comment]
Thank you for your dedication @marshallswain , I am going through the Vite page. It's fantastic, a lot, even a bit overwhelming..;)

At first glance, I can't find simple, complete vue template examples, maybe because there is no "search" yet in the docs. But, I can imagine some code to update an email or first/lastname field:

```vue
<template>
  your email: <input v-model="user.email">
  your lastname: <input v-model="user.lastName">
</template>

<script setup type="ts">
  // ... ?? ))
</script>
```

I know it sounds trivial to the experts, but this kind of things make booting something new for a newbie a pleasant experience)

**Comment by tvld** [comment]
About my choice to use the plugins folder: I know it's always a bit of a question where to put init scripts, so, my thoughts:

-  ``@/plugins`` folder >> main.ts is for initializing code that should be ready for the whole app, so that's pinia.ts as well
-  ``@/stores`` folder >> actual Pinia stores, where I like idea to use eg. ``users.pinia.ts`` and ``tasks.pinia.ts`` (so not replicate word 'store')
-  ``@/stores/schema`` folder >> what you call models, e.g. ``users.schema.ts``, ``tasks.schema.ts``  (note the 's', plural)

**Comment by marshallswain** [comment]
Ooh.  Thanks for the reminder.  I can finally add search to the docs, since I just got it working on feathersjs.com.

I'll add more examples to the docs after the rewrite.  I didn't want to write examples then do a rewrite and have to make slight changes to a bunch of code.  I'm actually going to focus on making example apps, like the vite example I've been working on: https://github.com/marshallswain/feathers-pinia-vite

Your planned folder structure seems reasonable.  I don't plan on having a schemas folder on the front end, since we'll be able to reuse the backend schemas.  Either way, though, the rewrite of feathers-pinia will be able to directly consume the schema types.

Models are the layer for modeling data and relationships between types. They reduce the amount of tightly coupled code you'd normally have to write in either component or store logic.

Schemas only produce an interface, but do not model your data for you, nor do they create typed data.  So the new models will build on schema types to produce a really nice dev experience.
