### ISSUE TITLE
Setup Experience 4 - useAuth cannot be named

### ISSUE THREAD

**Issue by tvld** [marshallswain/feathers-pinia#97]
Typescript error. Can not ``useAuth``. 

https://feathers-pinia.pages.dev/guide/auth-stores.html#setup
```ts
import { defineAuthStore } from 'feathers-pinia'
import { api as feathersClient } from '@/feathers' // NOTE, using  @ here and not ~

export const useAuth = defineAuthStore({  // error ts4023
  feathersClient,
})
```

```log
const useAuth: AuthStoreDefinition<string, {}, {}, {}>
Exported variable 'useAuth' has or is using name 'AuthStoreDefaultState' from external module ".../node_modules/feathers-pinia/dist/define-auth-store" but cannot be named.ts(4023)
```

**Comment by marshallswain** [comment]
@tvld, my recommendation is to use the latest pre-release.  `npm I feathers-pinia@pre`.  And use these docs: https://v1.feathers-pinia.pages.dev/

I've created a new `useAuth` utility which cleans up auth a lot and will replace the `defineAuthStore` plugin.  Here are the docs for it.  https://v1.feathers-pinia.pages.dev/guide/use-auth.html. It took a long time to figure out how to make it because I wanted something both simple and limitless, which I think we've achieved.

**Comment by marshallswain** [comment]
I'm labeling this as a docs issue, since I need to point the current docs site to the new one.

**Comment by marshallswain** [comment]
Also worth noting, I have a PR in the works that fixes all of the TypeScript issues and adds Dove types compatibility.  Here's the PR: https://github.com/marshallswain/feathers-pinia/pull/92.  

Docs are still pending, but you can read the test files to see how it works: https://github.com/marshallswain/feathers-pinia/blob/v1-use-store/tests/use-model/use-feathers-model.test.ts

Also, I put a really long explanation of the new architecture into Discord.  If you could login and read the #vue channel, I put a bunch of pre-docs content in there last night.

**Comment by marshallswain** [comment]
Please reopen if you experience this issue with the latest 2.0 pre-release and the `useAuth` utility.
